[package]
name = "runtime"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
async-trait.workspace = true
futures-util.workspace = true
toml.workspace = true
toml_edit = "0.22"
notify = "7"
common.workspace = true
ai-client.workspace = true
storage.workspace = true
tools = { path = "../tools" }

[dev-dependencies]
temp-env = "0.3"
serial_test = "3"